copyright: Copyright &copy; 2024 THOORENS Bruno - BSD licence
docs_dir: docs
extra_css:
- style.css
markdown_extensions:
- smarty
- def_list
- pymdownx.tasklist:
    custom_checkbox: false
nav:
- Home: index.md
- Bindings: bindings.md
- Serving: serving.md
- Request: request.md
- Encryption: encryption.md
- WSGI server: wsgi-server.md
repo_name: GitHub
repo_url: https://github.com/Moustikitos/micro-server
site_name: Python usrv project
theme:
  highlightjs: true
  hljs_languages:
  - python
  name: mkdocs
  nav_style: light
